//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Instructor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Instructor()
        {
            this.Courses = new HashSet<Course>();
        }
        [Key]
        public int Instructor_Id { get; set; }
        public string Instructor_Name { get; set; }
        public float Instructor_Salary { get; set; }

        [Column(TypeName = "date")]
        public DateTime Instructor_HireDate { get; set; }
        public Nullable<int> Branch_Id { get; set; }
        public Nullable<int> Manager_Id { get; set; }
        public Nullable<bool> isdeleted { get; set; }
        public int login_id { get; set; }
        [ForeignKey("Manager_Id")]
        public virtual Instructor Manager { get; set; }

        [ForeignKey("login_id")]
        public virtual Login_User Login_User { get; set; }

        public virtual Branch Branch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Course> Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Instructor> Instructors { get; set; }

    }
}
