//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_Answer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student_Answer()
        {
            this.MCQ_Answer = new HashSet<MCQ_Answer>();
            this.Text_Answer = new HashSet<Text_Answer>();
            this.TrueAndFalse_Answer = new HashSet<TrueAndFalse_Answer>();
        }
        [Key]
        public int Student_Answer_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Exam_Id { get; set; }
        public Nullable<int> Question_id { get; set; }
    
        public virtual Exam Exam { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MCQ_Answer> MCQ_Answer { get; set; }
        public virtual Question Question { get; set; }
        public virtual Student Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Text_Answer> Text_Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrueAndFalse_Answer> TrueAndFalse_Answer { get; set; }
    }
}
