//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Student_Answer = new HashSet<Student_Answer>();
            this.Student_Degree = new HashSet<Student_Degree>();
            this.Students_Course = new HashSet<Students_Course>();
        }
        [Key]
        public int Student_Id { get; set; }
        public string Student_Name { get; set; }
        [Column(TypeName="date")]
        public DateTime Student_BirthDate { get; set; }

        [StringLength(450)]
        [Index(IsUnique = true)]
        public string student_code { get; set; }

        public Nullable<bool> isdeleted { get; set; }
        public Nullable<int> login_id { get; set; }
        [ForeignKey("login_id")]
        public virtual Login_User Login_User { get; set; }

        public int Branch_Id { get; set; }
        public int Intake_Id { get; set; }
        public int Track_Id { get; set; }

        [ForeignKey("Branch_Id")]
        public virtual Branch Branch { get; set; }
        [ForeignKey("Intake_Id")]
        public virtual Intake Intake { get; set; }
        [ForeignKey("Track_Id")]
        public virtual Track Track { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Answer> Student_Answer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Degree> Student_Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Students_Course> Students_Course { get; set; }
    }
}
