//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Student_Degree
    {
        [Key]
        public int Student_Degree_Id { get; set; }
        public Nullable<int> Student_Id { get; set; }
        public Nullable<int> Exam_Id { get; set; }
        public int Degree { get; set; }

        public int isenterd { get; set; }

        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
