//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectex
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TrueAndFalse_Question
    {
        [Key]
        public int id { get; set; }
        public int Question_Id { get; set; }
        public bool TAndF_Correct_Answer { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
